name: Build and Push to JFrog Artifactory

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to JFrog Artifactory
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.JFROG_URL }}
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tags the image with the specific GitHub commit SHA for traceablity
          tags: |
            ${{ secrets.JFROG_URL }}/shrikant/container-practice:latest
            ${{ secrets.JFROG_URL }}/shrikant/container-practice:${{ github.sha }}

